services:
  - type: web
    name: crefasmvp
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn crefasmvp.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "django-insecure-gac=#_2n49ez+f3p#huf$n4)^4ivh!rl31yxw2f*g9+bt9ek()"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "crefasmvp.onrender.com"
    healthCheckPath: /
